jwt:
  secret: ${JWT_SECRET:43w11jzJHUOspQya0%2fd1Qg%3d%3d5by4Big0bkeRbAm54MN2ZA%3d%3d}
  expiration: ${JWT_EXPIRATION:1200000}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank}
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
