spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bank}
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
security.basic.enabled: false
management.security.enabled: false