version: '3.7'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bank
    container_name: database_app
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/.volumes/tqi/Postgresql/data:/var/lib/postgresql/data
    networks:
      - postgres-network
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_app
    environment:
      PGADMIN_DEFAULT_EMAIL: "foo@bar.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "54321:80"
    depends_on:
      - database
    networks:
      - postgres-network
  app:
    image: afonsobsneto/tqi_evolution
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: jdbc:postgresql://database_app:5432/bank
    depends_on:
      - database
    networks:
      - postgres-network
networks:
  postgres-network:
    driver: bridge